### ISSUE TITLE
TexSoup Error II

### ISSUE THREAD

**Issue by willsower** [hutchresearch/latex2speech#89]
Using this example document:

```LaTeX

\begin{document}

\begin{figure}
        \begin{minipage}[b]{0.5\linewidth}
                \centering \includegraphics[height=2in]{reg20.eps}
                \caption{Random tiling of square of side 20}\label{fig:g}   
        \end{minipage}%
\end{figure}

\end{document}
```

We get this error:

`EOFERROR: [Line: 0, Offset: 57] "figure" env expecting \end{figure}. Instead got \end{minipage}`

Initially I thought this was a TexParser problem, however it's erroring before even being passed to TexParser, and it's because of TexSoup. Here is the error log:

```LaTeX
127.0.0.1 - - [21/Apr/2021 11:34:44] "POST /form HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/application.py", line 215, in handle_form
    file_links = start_polly(file_holder, bib_holder)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/aws_polly_render.py", line 323, in start_polly
    expand_doc_new_labels(master[0])
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/expand_labels.py", line 101, in expand_doc_new_labels
    contents = replace_references(doc.read(), myHash)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/expand_labels.py", line 72, in replace_references
    myDoc = TexSoup.TexSoup(str(contents))
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/__init__.py", line 87, in TexSoup
    parsed, src = read(tex_code, skip_envs=skip_envs, tolerance=tolerance)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/tex.py", line 22, in read
    return TexEnv('[tex]', begin='', end='', contents=buf), tex
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/data.py", line 892, in __init__
    super().__init__(name, contents, args, preserve_whitespace, position)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/data.py", line 641, in __init__
    self._contents = list(contents) or []
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/reader.py", line 49, in read_tex
    yield read_expr(buf,
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/reader.py", line 109, in read_expr
    read_env(src, expr, tolerance=tolerance, mode=mode)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/reader.py", line 281, in read_env
    contents.append(read_expr(src, tolerance=tolerance, mode=mode))
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/reader.py", line 109, in read_expr
    read_env(src, expr, tolerance=tolerance, mode=mode)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/reader.py", line 284, in read_env
    unclosed_env_handler(src, expr, src.peek((0, 6)))
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/reader.py", line 186, in unclosed_env_handler
    raise EOFError('[Line: %d, Offset: %d] "%s" env expecting %s. %s' % (
EOFError: [Line: 0, Offset: 563] "figure" env expecting \end{figure}. Instead got \end{minipage}
```

As with Error I, this errors when TexSoup is being used in `expand_labels` file. Commenting out that file again, we get the same error with `expand_macros.` Here is the error log:

```LaTeX
Traceback (most recent call last):
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/application.py", line 215, in handle_form
    file_links = start_polly(file_holder, bib_holder)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/aws_polly_render.py", line 327, in start_polly
    parsed_contents = start_conversion(tex_file.read())
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/aws_polly_render.py", line 300, in start_conversion
    parsed_contents = parser.parse(contents)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/conversion_parser.py", line 360, in parse
    doc = expand_doc_macros(doc)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/expand_macros.py", line 158, in expand_doc_macros
    doc = normalize_doc_macros(doc)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/expand_macros.py", line 149, in normalize_doc_macros
    return TexSoup.TexSoup(text)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/__init__.py", line 87, in TexSoup
    parsed, src = read(tex_code, skip_envs=skip_envs, tolerance=tolerance)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/tex.py", line 22, in read
    return TexEnv('[tex]', begin='', end='', contents=buf), tex
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/data.py", line 892, in __init__
    super().__init__(name, contents, args, preserve_whitespace, position)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/data.py", line 641, in __init__
    self._contents = list(contents) or []
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/reader.py", line 49, in read_tex
    yield read_expr(buf,
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/reader.py", line 109, in read_expr
    read_env(src, expr, tolerance=tolerance, mode=mode)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/reader.py", line 281, in read_env
    contents.append(read_expr(src, tolerance=tolerance, mode=mode))
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/reader.py", line 109, in read_expr
    read_env(src, expr, tolerance=tolerance, mode=mode)
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/reader.py", line 284, in read_env
    unclosed_env_handler(src, expr, src.peek((0, 6)))
  File "/Users/taichen/Desktop/Tai/MyRepos/Tex2Speech/latex2speech/tex2speech/virt/lib/python3.8/site-packages/TexSoup/reader.py", line 186, in unclosed_env_handler
    raise EOFError('[Line: %d, Offset: %d] "%s" env expecting %s. %s' % (
EOFError: [Line: 0, Offset: 57] "figure" env expecting \end{figure}. Instead got \end{minipage}
```

**Comment by willsower** [comment]
Working on this in other issues
